<a href="https://colab.research.google.com/github/davisbyun/ai/blob/main/6_%EB%84%8C%ED%8C%8C%EC%9D%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy #넌파이설치

In [18]:
import numpy as np #넌파이 import

In [21]:
a = np.array(0) #1개 값 스칼라
print(a)
print(a.ndim)

0
0


In [22]:
a2 = np.array([1,2,3,4]) #벡터
print(a2)
type(a2)
print(a2.ndim)

[1 2 3 4]
1


In [27]:
a3 = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] ) #3X3 행렬
print(a3)
type(a3)
print(a3.ndim)
print(a3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [25]:
a4 = np.array (  [  [ [1,2],[3,4],[5,6]   ], [ [7,8],[9,10],[11,12]  ]  ]  ) #2면 3행 2열 텐서
print(a4)
type(a4)
print(a4.ndim)
print(a4.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [26]:
a5 = np.array (  [  [ [1,2],[3,4] ], [ [5,6],[7,8] ], [ [9,10],[11,12] ]  ]  ) #3면 2행 2열 텐서
print(a5)
type(a5)
print(a5.shape)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)


In [43]:
#reshaping
b=np.arange(12) #1차원 벡터 생성
print(b)
print(b.size,'~~~')

[ 0  1  2  3  4  5  6  7  8  9 10 11]
12 ~~~


In [32]:
b.shape
b.shape = 2,-1
print(b)
b.shape

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


(2, 6)

In [34]:
b.shape = 3, -1
print(b)
b.shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


(3, 4)

In [36]:
b.shape = -1, 1
print(b)
b.shape

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


(12, 1)

In [44]:
b.shape =-1, 3
print(b)
b.shape
print(b.size)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
12


In [40]:
b.shape = -1
print(b)
b.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11]


(12,)

In [41]:
c=np.arange(13) #1차원 벡터 생성
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [42]:
c.shape
c.shape = 2,-1
print(c)
c.shape  #요소의 갯수가 홀수로 갯수가 맞지 않아 에러 발생

NameError: name 'c' is not defined

- 자료형
  - int 형 (정수)
    - int64, int16, int8, uint64(uint는 양수로만 표현, int는 양수와 음수 범위의 수이며 int다음의 숫자는 Bit를 의미 예)int64--> 64비트로   )
    - -2^63~2^63-1
    - -2^15~2^15-1
    - uint64 -> 0~2^127의 정수 표현의 범위 양의정수만 구한다
  - float 형 (실수) - 부동소수점 표현 방식 또는 실수 표현방식(검색시 키워드)
    - float64, float16, float8
    - 자료저장모습 = 부호비트 1비트 지수부 7비트 가수부(8 or 24 or 58)
    - 소수점 아래 저장하는 공간이 많아지게 하는 것
    - 실수의 기본은 float64
  - complex 형 (복소수)


In [47]:
a=np.array([1,3,5,7,9]), np.int32
print(a)
a.dtype

(array([1, 3, 5, 7, 9]), <class 'numpy.int32'>)


AttributeError: 'tuple' object has no attribute 'dtype'

In [61]:
a=np.array([1,3,5,7,9]), np.int32 #int32의 자료표현 범위? (–2,147,483,648~2,147,483,647)
print(a)
a1=np.array([2147483645, 2147483646, 2147483647 ], np.int32 ) #범위 내의 값
print(a)

(array([1, 3, 5, 7, 9]), <class 'numpy.int32'>)
(array([1, 3, 5, 7, 9]), <class 'numpy.int32'>)


In [51]:
a=np.array([1,3,5,7,9]), np.int32 #int32의 자료표현 범위? (–2,147,483,648~2,147,483,647)
print(a)
a1=np.array([2147483646, 2147483647, 2147483649 ], np.int32 ) #범위 밖의 값
print(a)

(array([1, 3, 5, 7, 9]), <class 'numpy.int32'>)
(array([1, 3, 5, 7, 9]), <class 'numpy.int32'>)


<ipython-input-51-42647a0e2c28>:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2147483649 to int32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a1=np.array([2147483646, 2147483647, 2147483649 ], np.int32 )


In [53]:
a=np.array([1,3,5,7,9]), np.int64
print(a)
a1=np.array([2147483646, 2147483647, 2147483648 ], np.int32 ) #범위 밖의 값
print(a)

(array([1, 3, 5, 7, 9]), <class 'numpy.int64'>)
(array([1, 3, 5, 7, 9]), <class 'numpy.int64'>)


<ipython-input-53-9d166e6d6809>:3: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2147483648 to int32 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a1=np.array([2147483646, 2147483647, 2147483648 ], np.int32 )


In [56]:
a2=np.array([2**63, 2**63+1, 2**63+2], np.uint64)
print(a2)
a2.dtype

[9223372036854775808 9223372036854775809 9223372036854775810]


dtype('uint64')

In [58]:
a3=np.array( [2**62, -2**62 ] )
print(a3)
a3.dtype

[ 4611686018427387904 -4611686018427387904]


dtype('int64')

In [59]:
a4=np.array([1,3,5,7,9])  #자료형을 명시하지 않으면 int는 기본이 64비트이며 범위가 작다면 int32, int16, int8로 명시하여 데이터를 아낄 수 있다
print(a4)
a4.dtype

[1 3 5 7 9]


dtype('int64')

In [66]:
a = np.array(3.141592653589793, np.float16) #소숫점 2자리까지 정확
print(a)
a.dtype

3.14


dtype('float16')

In [64]:
a = np.array(3.141592653589793, np.float32) #소숫점 6자리까지 정확
print(a)
a.dtype

3.1415927


dtype('float32')

In [65]:
a = np.array(3.141592653589793, np.float64) #소숫점 15자리까지 정확
print(a)
a.dtype

3.141592653589793


dtype('float64')

In [67]:
a = np.array(3.141592653589793) #기본은 float64임, 소숫점 15자리까지 정확
print(a)
a.dtype

3.141592653589793


dtype('float64')

In [72]:
a = np.array(  [1,2j,3+4j,2.72+3.14j  ])
print(a)
a.dtype
a.real #실수만 추출
a.imag #허수만 추출
print(a.real.dtype)
print(a.imag.dtype)

[1.  +0.j   0.  +2.j   3.  +4.j   2.72+3.14j]
float64
float64


1. 인덱싱 indexing
  1) 1DArray
  2) 2DArray
2. 슬라이싱 slicing
  1) 1DArray
  2) 2DArray  
3. leterating
  1) 1DArray
  2) 2DArray  


In [80]:
a=np.array([1,3,5,7,9])
print(a)
print(a.ndim)
print(a.shape)
print(a[0])
print(a[3])
print(a[-1])
print(a[-2])

[1 3 5 7 9]
1
(5,)
1
7
9
7


In [89]:
a2 = np.array( [ [1,3,5],[2,4,6] ] )
print(a2)
print(a2.ndim)
print(a2.shape)
#1,5,4 추출
print([ a2[0,0], a2[0,2], a2[1,1]])
#6,3 추출
print(a2[1,2], a2[0,1])

[[1 3 5]
 [2 4 6]]
2
(2, 3)
[1, 5, 4]
6 3
[[ 1  3  5]
 [25  4  6]]


In [91]:
#3->13
a2[0,1]=13
#2->25
a2[1,0]=25
print(a2)

[[ 1 13  5]
 [25  4  6]]


In [92]:
#0번행 전체의 값에다 +10하기
print([a2[0]])
print([a2[0, :]])
print(a2[0,0:3])
a2[0] = a[0] +10
print(a2[0])

[array([ 1, 13,  5])]
[array([ 1, 13,  5])]
[ 1 13  5]
[11 11 11]


In [96]:
#1번행 전체의 값에다 *2 하기
a2[1] = a[1] *2
a2[1] *= 2
#1번행 전체의 값에다 *2 하기
a2[ :,1:2 ] = a2[ :, 1:2] /2
print(a2)

[[11  1 11]
 [12  6 12]]


In [107]:
a=np.array([1,3,5,7,9])
print(a.ndim)
print(a.shape)
print(a[:])
print(a[0:])
print(a[1:])
print(a[2:])
print(a[3:])
print(a[:0])
print(a[:1])
print(a[:2])
#print(a[1,3,5])에러발생
print(a[:-1])
print(a[:-2])
print(a[1:4])


1
(5,)
[1 3 5 7 9]
[1 3 5 7 9]
[3 5 7 9]
[5 7 9]
[7 9]
[]
[1]
[1 3]
[1 3 5 7]
[1 3 5]
[3 5 7]


In [117]:
a2=np.arange(10) #0~9까지 연속적인 수의 배열
print(a2)
print(a2[::2]) #처음인덱스:끝인덱스:증가인덱스 < 끝인덱스 -1 임 끝은 미포함 >
print(a2[::3])
print(a2[::4])
print(a2[::-1])
print(a2[::-2])
print(a2[1::2])
print(a2[:-2:2])
print(a2[:-4:2])
print(a2[2:-2:2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[0 4 8]
[9 8 7 6 5 4 3 2 1 0]
[9 7 5 3 1]
[1 3 5 7 9]
[0 2 4 6]
[0 2 4]
[2 4 6]


In [129]:
a3=np.arange(15)
print(a3)
print(a3[1:10:2])
print(a3[2:11:2])
print(a3[:9:-1])
print(a3[:])
print(a3[1:2])
print(a3[-1:-2:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1 3 5 7 9]
[ 2  4  6  8 10]
[14 13 12 11 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[1]
[14]


In [139]:
#슬라이싱 slicing 2D Array
a=np.arange(10,25).reshape(3,5)
print(a)
print(a.ndim)
print(a.shape)
print(a[:])
print(a[0:])
print(a[1:])
print(a[-1:])
print(a[-2:])
print(a[-3:])
print(a[:0],'ccc')
print(a[:1], 'ddd')
print(a[:-1], 'aaa')

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
2
(3, 5)
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[15 16 17 18 19]
 [20 21 22 23 24]]
[[20 21 22 23 24]]
[[15 16 17 18 19]
 [20 21 22 23 24]]
[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[] ccc
[[10 11 12 13 14]] ddd
[[10 11 12 13 14]
 [15 16 17 18 19]] aaa


In [140]:
print( a[ : , 0: ] )

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [141]:
print( a[ : , 1: ] )

[[11 12 13 14]
 [16 17 18 19]
 [21 22 23 24]]


In [142]:
print( a[ : , -3: ] )

[[12 13 14]
 [17 18 19]
 [22 23 24]]


In [143]:
print( a[ : , 1:-1 ] )

[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [144]:
print( a[ 1: , 1:3 ] )

[[16 17]
 [21 22]]


In [147]:
print( a[ : , -2: ] )

[[13 14]
 [18 19]
 [23 24]]


In [150]:
a=np.arange(10,100).reshape(9,10)
print(a)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [151]:
print(a[:3, : ] )

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]


In [154]:
print(a[ 1:5, -4:-1 ] )

[[26 27 28]
 [36 37 38]
 [46 47 48]
 [56 57 58]]


In [156]:
#leterating 반복자  1DArray
a=np.arange(11)**2
print(a)

[  0   1   4   9  16  25  36  49  64  81 100]


In [157]:
a=np.arange(11)**3
print(a)

[   0    1    8   27   64  125  216  343  512  729 1000]


In [158]:
for a1 in a :
  print(a1)

0
1
8
27
64
125
216
343
512
729
1000


In [160]:
#leterating 반복자 2DArray
#10~21까지 3행 4열 배역
b=np.arange(10,22).reshape(3,4)
print(b)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [161]:
for bb in b :
  print(bb) #한 행씩 출력

[10 11 12 13]
[14 15 16 17]
[18 19 20 21]


In [162]:
#요소별로 출력
for b1 in b :
  for b2 in b1 :
    print(b2)

10
11
12
13
14
15
16
17
18
19
20
21


### 배열의 명령어
  - arnage
    - 형식 : np.arange([시작수,] 끝수[, 증가수, 자료형]  )
  - linespace
  - transpose
  - reshape
  - r_
  - c_
  - concatenate
  - hstack, vstack
  - zeros
  - ones
  - full
  - empty

In [163]:
#arnage
a=np.arange(10, 101, 5)
print(a)

[ 10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90  95
 100]


In [170]:
a=np.arange(10, dtype=np.float32)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [177]:
#0, 0.1, 0,2 ...0.9
a=np.arange(0, 1.0, 0.1)
print(a)
print(a.dtype)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
float64


In [180]:
#linespace  시작수 끝수 갯수
a=np.linspace(0, 100, 11)
print(a)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [183]:
#transpose
a=np.array( [ [1,2,3],[4,5,6] ] )
b=a.T #0열->0행으로 1열->1행
print(a)
print(b)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [184]:
#transpose
a=np.array( [ [1,2,3],[4,5,6] ] )
b=a.T #0열->0행으로 1열->1행 (열을 행으로)
print(a)
print(b)
b2=np.transpose(a) ##0열->0행으로 1열->1행 (열을 행으로)
print(b2)

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [186]:
bb2=np.transpose(b2) ##0열->0행으로 1열->1행 (열을 행으로)
print(bb2)
aa=b.T
print(aa)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


In [187]:
#reshape (행수, 열수)
a=np.array([1,2,3,4,5,6]).reshape(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [188]:
#r_  - row 행으로 합치기
a=np.array([1,2,3])
b=np.array([4,5,6,7])
print(a)
print(b)
c=np.r_[a,b]
print(c)


[1 2 3]
[4 5 6 7]
[1 2 3 4 5 6 7]


In [190]:
#c_ - colunm 을 열행태로 합치기
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a)
print(b)
c=np.c_[a,b]
print(c)

[1 2 3]
[4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [193]:
#concatenate
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b), axis=0)  #a,b배열을 행으로 합치기
print(c)

[1 2 3 4 5 6]


In [196]:
a=np.array( [ [1,2],[3,4] ] )
b=np.array( [ [5,6],[7,8] ] )
print(a)
print(b)
c=np.concatenate((a,b))  #행으로 합치기
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [195]:
a=np.array( [ [1,2],[3,4] ] )
b=np.array( [ [5,6],[7,8] ] )
print(a)
print(b)
c=np.concatenate((a,b), axis=1)  #열로 합치기
print(c)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [198]:
a=np.array( [ [1,2],[3,4] ] )
b=np.array( [ [5,6],[7,8] ] )
print(a)
print(b)
c=np.r_[a,b] #열로 합치기
print(c)
d=np.c_[a,b] #행으로 합치기
print(d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [202]:
#hstack - 수평 vstack -수직
a=np.array( [ [1,2],[3,4] ] )
b=np.array( [ [5,6],[7,8] ] )
c=np.hstack((a,b))   #행으로 합치기        # ()튜플 {} 딕셔너리 [] list
print(c)
d=np.vstack((a,b))   #열로 합치기
print(d)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [204]:
a=np.zeros(5)
print(a)
a=np.ones(5)
print(a)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [205]:
a2=np.zeros((3,5))
print(a2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [209]:
a3=np.ones((5,4))
print(a3)
print(a3.dtype)
print(a3.ndim)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
float64
2


In [212]:
a=np.full(5,3)
print(a)

[3 3 3 3 3]


In [214]:
c= a2=np.full((3,4), 7 )
print(c)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [219]:
#empty 항목을 초기화하지 않고 주어진 모양과 유형의 새배열을 반환
a=np.empty(4)
print(a)

a=np.empty(4, dtype=np.int64)
print(a)

b=np.empty((2,4), dtype=np.int32 )
print(b)

[2.5e-323 3.0e-323 3.5e-323 4.0e-323]
[5 6 7 8]
[[5 0 6 0]
 [7 0 8 0]]


### Math Operation 수학함수 명령어들
- Broadcasting -,+,x, /  
- Matrix Multiplication
- 제곱근, 제곱합
- 합계
- 누적합계
- 평균

In [229]:
#Broadcasting
a= np.array( [ [1,2,3 ] , [ 4,5,6 ] ] )
b= np.array( [ [2,2,2 ] , [ 3,3,3 ] ] )
print(a+b)
print(a-b)
print(a/b)
print(a**b)
print(a%b)

[[20 20]
 [47 47]]
[[20 20]
 [47 47]]


In [230]:
#행렬 곱하기
a= np.array( [ [1,2,3 ] , [ 4,5,6 ] ] )
b= np.array( [ [2,2 ] , [ 3,3 ] , [4,4] ] )
c= a@b
print(c)
d=np.matmul(a,b)
print(d)


[[20 20]
 [47 47]]
[[20 20]
 [47 47]]


In [231]:
#제곱
a=np.array([1,2,3,4])
a1=np.square(a)
print(a1)


[ 1  4  9 16]


In [232]:
#제곱근
a=np.array([1,2,3,4])
print(np.sqrt(a))

[1.         1.41421356 1.73205081 2.        ]


In [233]:
#합계
print(np.sum(a))

10


In [237]:
#평균
print(np.average(a))
#평균
print(np.mean(a))
#최대값
print(np.max(a))
#최소값
print(np.min(a))

2.5
2.5
4
1


In [240]:
#누적합
a=np.array([1,2,3,4,5])
print(np.cumsum(a))

[ 1  3  6 10 15]


In [242]:
#누적곱
a=np.arange(1,7)
print(a)
print(np.cumprod(a))

[1 2 3 4 5 6]
[  1   2   6  24 120 720]


- pi
- e
- exp
- sin
- cos
- tan
- log


In [248]:
from numpy import pi, e
print(pi)
print(e)


3.141592653589793
2.718281828459045


In [251]:
import numpy as np
np.exp(1)
x= np.array([0,1,2])
y=np.exp(x)
print(y)

[1.         2.71828183 7.3890561 ]


In [258]:
import matplotlib.pyplot as plt #그래프그리는 라이브러리

In [ ]:
y=np.linspace(-2, 2, 100)
y=np.exp(y)
plt.plot( x, y )
plt.show()

- random - 난수 rand


In [265]:
np.random.rand()
print(np.random.rand(3)) #3열의 랜덤수
print(np.random.rand(3,5)) #3행5열 랜덤수

[0.51101918 0.90111713 0.40053893]
[[0.75669652 0.946634   0.60442251 0.57455339 0.49599035]
 [0.97308186 0.23665406 0.24119489 0.42033486 0.19596605]
 [0.6877592  0.50895613 0.73657461 0.88556472 0.02896947]]


- 파일로 저장하기 np.save('파일명.npy', 넘파이자료)
- 파일로 불러오기 np.load('파일명')

In [267]:
#0~99까지 출력 10행 10열 배열
a=np.arange(0,100).reshape(10,10)
print(a)
np.save('test.npy', a)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [269]:
# 넘파이 불러오기
k=np.load('test.npy')
print(k)


[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#우수 초콜릿 분석하기

In [270]:
import numpy as np

In [280]:
from google.colab import files
f = files.upload()


Saving chocolate_rating.csv to chocolate_rating.csv


In [282]:
data=np.loadtxt('chocolate_rating.csv', delimiter=',')

In [285]:
print(data.ndim)
print(data.shape)
print(data.size)

2
(1795, 4)
7180


In [287]:
rating_mean=data[ : , 3 ].mean()
print(rating_mean)

3.185933147632312


In [294]:
high_level=data[ data[ :, 3]>=4]
print(high_level[0:10])

[[1.000e+01 2.014e+03 7.000e-01 4.000e+00]
 [1.800e+01 2.013e+03 7.000e-01 4.000e+00]
 [2.100e+01 2.013e+03 6.300e-01 4.000e+00]
 [5.500e+01 2.011e+03 7.000e-01 4.000e+00]
 [5.700e+01 2.010e+03 7.000e-01 4.000e+00]
 [7.700e+01 2.007e+03 7.000e-01 4.000e+00]
 [7.800e+01 2.007e+03 7.500e-01 4.000e+00]
 [7.900e+01 2.007e+03 7.000e-01 5.000e+00]
 [8.400e+01 2.007e+03 7.000e-01 4.000e+00]
 [8.700e+01 2.006e+03 7.000e-01 5.000e+00]]


In [299]:
print(high_level[ :, 0 ])
high_id = high_level[ :, 0 ].astype(np.int64)
print(high_id)
print(high_id.size)


[  10.   18.   21.   55.   57.   77.   78.   79.   84.   87.   88.   93.
  108.  109.  118.  124.  153.  180.  181.  187.  223.  232.  233.  240.
  243.  244.  245.  248.  257.  312.  316.  317.  358.  437.  503.  567.
  573.  574.  582.  601.  650.  687.  690.  691.  701.  720.  730.  800.
  828.  862.  864.  865.  866.  883.  919.  993. 1088. 1089. 1118. 1119.
 1120. 1204. 1241. 1245. 1247. 1274. 1277. 1278. 1289. 1291. 1293. 1295.
 1323. 1331. 1336. 1378. 1394. 1426. 1428. 1433. 1479. 1488. 1513. 1516.
 1529. 1530. 1531. 1533. 1536. 1537. 1544. 1545. 1664. 1683. 1686. 1688.
 1694. 1700. 1740. 1757.]
[  10   18   21   55   57   77   78   79   84   87   88   93  108  109
  118  124  153  180  181  187  223  232  233  240  243  244  245  248
  257  312  316  317  358  437  503  567  573  574  582  601  650  687
  690  691  701  720  730  800  828  862  864  865  866  883  919  993
 1088 1089 1118 1119 1120 1204 1241 1245 1247 1274 1277 1278 1289 1291
 1293 1295 1323 1331 1336 1378 1394

In [305]:
high_kakao = high_level[:,2]
unique_values, value_counts = np.unique(high_kakao, return_counts=True)
print('카카오 함유량:', unique_values)
print('함유량별 빈도수:', value_counts)

카카오 함유량: [0.6  0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7  0.71 0.72 0.73 0.74 0.75
 0.78 0.8  0.88]
함유량별 빈도수: [ 1  3  4  2  1  3  2  2 45  1 11  1  4 17  1  1  1]


In [306]:
max_index = np.argmax(value_counts)
print(unique_values[max_index])
print('우수 초콜릿', high_id.size, '가지 중', value_counts[max_index],\
 '가지의 카카오 함유량이', unique_values[max_index] * 100, '%입니다.')

0.7
우수 초콜릿 100 가지 중 45 가지의 카카오 함유량이 70.0 %입니다.
